language: node_js


node_js:
   - "0.10"

before_script:
   - sudo rm -rf /usr/local/phantomjs
   - curl -L -O https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.7-linux-x86_64.tar.bz2
   - tar xjf phantomjs-1.9.7-linux-x86_64.tar.bz2
   - sudo mv phantomjs-1.9.7-linux-x86_64 /usr/local/phantomjs
   - git clone -q git://github.com/n1k0/casperjs.git
   - cd casperjs; git checkout -q tags/1.1-beta1; cd ../
   - export PATH=$PATH:`pwd`/casperjs/bin  
   - phantomjs --version; casperjs --version

before_install:
   - git submodule update --init --recursive

install:
   - npm install -g grunt-cli bower@1.3.6
   - bower install
   - cd tests; npm install 

script: cd tests;npm test 
